import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";
import eslintConfigPrettier from "eslint-config-prettier/flat";

export default tseslint.config(
  // `dist` is build output; `supabase/functions/bundle` is generated by
  // scripts/bundle-functions.sh. Neither is source, and linting generated
  // JavaScript produces noise that hides real problems.
  { ignores: ["dist", "supabase/functions/bundle/ai-admin.ts"] },
  {
    extends: [
      js.configs.recommended,
      ...tseslint.configs.recommended,
      eslintConfigPrettier,
    ],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": [
        "warn",
        { allowConstantExport: true },
      ],
    },
  },
  {
    // The edge functions are Deno, linted by `deno lint` (clean, 11 files).
    // Running the browser ESLint config over them produces false positives that
    // are actively misleading:
    //
    //   • `no-useless-escape` flags `\/` inside a character class. It is NOT
    //     useless in a regex literal: an unescaped `/` terminates the literal.
    //     That exact bug once stopped the Spring route parser from parsing.
    //   • `no-explicit-any` fires on the service-role client, which is
    //     deliberately open-typed because this project has no generated
    //     `Database` type. `deno.json` already excludes the same rule.
    files: ["supabase/functions/**/*.ts"],
    rules: {
      "no-useless-escape": "off",
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
);
